### ISSUE TITLE
Submodel Predictions does not restore correctly

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#246]
As a user I want all submodels to appear.
As a developer, I should be able to mimic how Normalization is working.

Simply check to see how many max/mins there are, and then click the `Add submodel prediction` button that many times

**Comment by ryanbanderson** [comment]
Restoring submodel predicitons seems to be working fine for me. Closing.

**Comment by ryanbanderson** [comment]
Nevermind. Seems like connecting the submodel comboboxes so that they update when data is changed makes them get overwritten right after restoring...

**Comment by ryanbanderson** [comment]
Ok, so I think I fixed it. In the end the solution was just to capitalize the object name for the choose data combo box so that it gets restored before the submodel combo boxes rather than after. That way, the saved contents for the submodel boxes overwrites the "no predictions available" message rather than vice versa.
